export enum UtilityEnum {
    NEW_BOARD_MODAL = "new-board-modal",
    BOARD_INPUT_BLOCK_ID = "board-input-block-id",
    BOARD_INPUT_LABEL = "Board Name",
    BOARD_NAME_ACTION_ID = "board-name-action-id",
    BOARD_INPUT_PLACEHOLDER = "Enter Board Name",
    SUBMIT = "Submit",
    AUTHORIZE = "Authorize",
    CANCEL = "Cancel",
    SUBMIT_ACTION_ID = "submit-action-id",
    SUBMIT_BLOCK_ID = "submit-block-id",
    CLOSE = "Close",
    CLOSE_ACTION_ID = "close-action-id",
    CLOSE_BLOCK_ID = "close-block-id",
    NEW_BOARD_TITLE = "Create New Whiteboard",
    AUTH_LABEL = "Do you want to authorize this app to use your account details?",
    AUTH_MODAL = "auth-modal",
    AUTH_TITLE = "Authorization",
    DELETE_BOARD_TITLE = "Delete Whiteboard",
    DELETE_BOARD_MODAL = "delete-board-modal",
    PREVIEW_BLOCK_ID = "preview-block-id",
    PREVIEW_BLOCK_TITLE = "Whiteboard Preview",
    PREVIEW_BUTTON_ACTION_ID = "preview-button-action-id",
    OPEN_BUTTON_ACTION_ID = "open-button-action-id",
    SAVE_BUTTON_ACTION_ID = "save-button-action-id",
    RENAME_BUTTON_ACTION_ID = "rename-button-action-id",
    CREATE_WHITEBOARD_MESSAGE_BOX_ACTION_ID = "create-whiteboard-message-box-action-id",
}
